language: python

python:
  - "3.7"

dist: xenial

sudo: false

services:
  - docker

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/operator-engine
    python: 3.7
